import type { Metadata } from 'next';
import { NOINDEX } from '@/lib/flags';
import { site } from '@/content/site';

/**
 * Section 13 — SEO plumbing in one place.
 *
 * Every page gets a unique title and description, a canonical, and an OG image.
 * While NOINDEX is true the robots directives say so on every response; the
 * canonical and the structured data are still emitted, so nothing has to be
 * rewired on the day the flag flips.
 *
 * No third party is contacted to do any of this (Section 4.3): the OG images
 * are generated in-process from the vendored fonts.
 */

function resolveBaseUrl(): string {
  const raw = process.env.NEXT_PUBLIC_BASE_URL;
  if (!raw) return 'http://localhost:3000';
  return raw.replace(/\/$/, '');
}

export const BASE_URL = resolveBaseUrl();

export const robotsDirective = NOINDEX
  ? { index: false, follow: false, nocache: true }
  : { index: true, follow: true };

export type PageSeo = {
  /** Page title, without the ' · Rumiq' suffix — the template adds it. */
  title: string;
  description: string;
  /** Absolute path, leading slash, no trailing slash except the root. */
  path: string;
  /** Set for editorial pages so the OG card and the JSON-LD agree. */
  type?: 'website' | 'article';
  publishedTime?: string;
  /**
   * Route of the OG image for this page. Defaults to the site card generated by
   * app/opengraph-image.tsx.
   *
   * This has to be explicit: Next only merges a file-based OG image into a page
   * that does not declare its own `openGraph` object, and every page here does,
   * because every page needs its own title and description. Naming the image
   * route is what keeps og:image present on all of them.
   */
  ogImagePath?: string;
};

/** Builds the Metadata object for a page. Used by every route. */
export function pageMetadata({
  title,
  description,
  path,
  type = 'website',
  publishedTime,
  ogImagePath = '/opengraph-image',
}: PageSeo): Metadata {
  const url = `${BASE_URL}${path}`;
  const images = [
    { url: `${BASE_URL}${ogImagePath}`, width: 1200, height: 630, alt: `${title} · ${site.name}` },
  ];

  return {
    title,
    description,
    alternates: { canonical: url },
    robots: robotsDirective,
    openGraph: {
      title: `${title} · ${site.name}`,
      description,
      url,
      siteName: site.name,
      type,
      locale: 'en',
      images,
      ...(publishedTime ? { publishedTime } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: `${title} · ${site.name}`,
      description,
      images,
    },
  };
}

/* ---------------------------------------------------------------------------
   JSON-LD builders. Section 13.

   Nothing here may assert a claim the site does not make elsewhere: no awards,
   no ratings, no review counts, no certification (Section 4.2).
   --------------------------------------------------------------------------- */

export function organisationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': `${BASE_URL}/#organisation`,
    name: site.name,
    legalName: site.legalEntity,
    url: `${BASE_URL}/`,
    description:
      'Rumiq connects marketing, patient access and operational data into one governed view of healthcare growth.',
    address: { '@type': 'PostalAddress', addressLocality: 'Dubai', addressRegion: 'DIFC', addressCountry: 'AE' },
  };
}

export function websiteJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${BASE_URL}/#website`,
    name: site.name,
    url: `${BASE_URL}/`,
    publisher: { '@id': `${BASE_URL}/#organisation` },
    inLanguage: 'en',
  };
}

export function webPageJsonLd({ title, description, path }: { title: string; description: string; path: string }) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': `${BASE_URL}${path}#page`,
    name: title,
    description,
    url: `${BASE_URL}${path}`,
    isPartOf: { '@id': `${BASE_URL}/#website` },
    inLanguage: 'en',
  };
}

export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((step, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: step.name,
      item: `${BASE_URL}${step.path}`,
    })),
  };
}

/** Only ever called with Document 05 entries. Returns null when there are none,
 *  so no empty FAQPage node is emitted (Section 15). */
export function faqJsonLd(entries: { question: string; plainAnswer: string }[]) {
  if (!entries.length) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: entries.map((entry) => ({
      '@type': 'Question',
      name: entry.question,
      acceptedAnswer: { '@type': 'Answer', text: entry.plainAnswer },
    })),
  };
}

export function articleJsonLd({
  title,
  description,
  path,
  published,
  updated,
}: {
  title: string;
  description: string;
  path: string;
  published: string;
  updated?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: title,
    description,
    url: `${BASE_URL}${path}`,
    datePublished: published,
    dateModified: updated ?? published,
    author: { '@id': `${BASE_URL}/#organisation` },
    publisher: { '@id': `${BASE_URL}/#organisation` },
    isPartOf: { '@id': `${BASE_URL}/#website` },
    inLanguage: 'en',
  };
}
